/* Generated file with "scripts/generate-metasdk.ts" */

import { EndpointDef } from "./endpoint-defs-type";

export const ENDPOINT_DEFS: EndpointDef[] = [
  {
    "url": "/audio/text/audio-transcription/",
    "inputType": "audio",
    "outputType": "text",
    "taskName": "audio-transcription",
    "models": [
      "large-v2"
    ],
    "defaultModel": "large-v2",
    "inputBodyContentType": "multipart/form-data",
    "outputBodyContentType": {
      "type": "prediction-standard-output",
      "predictionType": {
        "array": "object"
      }
    },
    "params": [
      {
        "in": "formData",
        "type": "audio",
        "name": "audio",
        "example": "http://files.gladia.io/example/audio-transcription/split_infinity.wav",
        "required": false
      },
      {
        "in": "formData",
        "type": "url",
        "name": "audio_url",
        "example": "http://files.gladia.io/example/audio-transcription/split_infinity.wav",
        "required": false
      },
      {
        "in": "formData",
        "type": "enum",
        "name": "language_behaviour",
        "example": "automatic single language",
        "required": false,
        "enumValues": [
          "manual",
          "automatic single language",
          "automatic multiple languages"
        ]
      },
      {
        "in": "formData",
        "type": "enum",
        "name": "language",
        "example": "english",
        "required": false,
        "enumValues": [
          "afrikaans",
          "albanian",
          "amharic",
          "arabic",
          "armenian",
          "assamese",
          "azerbaijani",
          "bashkir",
          "basque",
          "belarusian",
          "bengali",
          "bosnian",
          "breton",
          "bulgarian",
          "catalan",
          "chinese",
          "croatian",
          "czech",
          "danish",
          "dutch",
          "english",
          "estonian",
          "faroese",
          "finnish",
          "french",
          "galician",
          "georgian",
          "german",
          "greek",
          "gujarati",
          "haitian creole",
          "hausa",
          "hawaiian",
          "hebrew",
          "hindi",
          "hungarian",
          "icelandic",
          "indonesian",
          "italian",
          "japanese",
          "javanese",
          "kannada",
          "kazakh",
          "khmer",
          "korean",
          "lao",
          "latin",
          "latvian",
          "lingala",
          "lithuanian",
          "luxembourgish",
          "macedonian",
          "malagasy",
          "malay",
          "malayalam",
          "maltese",
          "maori",
          "marathi",
          "mongolian",
          "myanmar",
          "nepali",
          "norwegian",
          "nynorsk",
          "occitan",
          "pashto",
          "persian",
          "polish",
          "portuguese",
          "punjabi",
          "romanian",
          "russian",
          "sanskrit",
          "serbian",
          "shona",
          "sindhi",
          "sinhala",
          "slovak",
          "slovenian",
          "somali",
          "spanish",
          "sundanese",
          "swahili",
          "swedish",
          "tagalog",
          "tajik",
          "tamil",
          "tatar",
          "telugu",
          "thai",
          "tibetan",
          "turkish",
          "turkmen",
          "ukrainian",
          "urdu",
          "uzbek",
          "vietnamese",
          "welsh",
          "wolof",
          "yiddish",
          "yoruba"
        ]
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_noise_reduction",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "string",
        "name": "transcription_hint",
        "example": "",
        "required": false
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_diarization",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_direct_translate",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "enum",
        "name": "target_translation_language",
        "example": "english",
        "required": false,
        "enumValues": [
          "afrikaans",
          "albanian",
          "amharic",
          "arabic",
          "armenian",
          "assamese",
          "azerbaijani",
          "bashkir",
          "basque",
          "belarusian",
          "bengali",
          "bosnian",
          "breton",
          "bulgarian",
          "catalan",
          "chinese",
          "croatian",
          "czech",
          "danish",
          "dutch",
          "english",
          "estonian",
          "faroese",
          "finnish",
          "french",
          "galician",
          "georgian",
          "german",
          "greek",
          "gujarati",
          "haitian creole",
          "hausa",
          "hawaiian",
          "hebrew",
          "hindi",
          "hungarian",
          "icelandic",
          "indonesian",
          "italian",
          "japanese",
          "javanese",
          "kannada",
          "kazakh",
          "khmer",
          "korean",
          "lao",
          "latin",
          "latvian",
          "lingala",
          "lithuanian",
          "luxembourgish",
          "macedonian",
          "malagasy",
          "malay",
          "malayalam",
          "maltese",
          "maori",
          "marathi",
          "mongolian",
          "myanmar",
          "nepali",
          "norwegian",
          "nynorsk",
          "occitan",
          "pashto",
          "persian",
          "polish",
          "portuguese",
          "punjabi",
          "romanian",
          "russian",
          "sanskrit",
          "serbian",
          "shona",
          "sindhi",
          "sinhala",
          "slovak",
          "slovenian",
          "somali",
          "spanish",
          "sundanese",
          "swahili",
          "swedish",
          "tagalog",
          "tajik",
          "tamil",
          "tatar",
          "telugu",
          "thai",
          "tibetan",
          "turkish",
          "turkmen",
          "ukrainian",
          "urdu",
          "uzbek",
          "vietnamese",
          "welsh",
          "wolof",
          "yiddish",
          "yoruba"
        ]
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_text_emotion_recognition",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_summarization",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_chapterization",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "integer",
        "name": "diarization_max_speakers",
        "example": 10,
        "required": false
      },
      {
        "in": "formData",
        "type": "enum",
        "name": "output_format",
        "example": "json",
        "required": false,
        "enumValues": [
          "json",
          "srt",
          "vtt",
          "txt",
          "plain"
        ]
      }
    ],
    "hasSamplesParam": false
  },
  {
    "url": "/video/text/video-transcription/",
    "inputType": "video",
    "outputType": "text",
    "taskName": "video-transcription",
    "models": [
      "large-v2"
    ],
    "defaultModel": "large-v2",
    "inputBodyContentType": "multipart/form-data",
    "outputBodyContentType": {
      "type": "prediction-standard-output",
      "predictionType": {
        "array": "object"
      }
    },
    "params": [
      {
        "in": "formData",
        "type": "video",
        "name": "video",
        "example": "http://files.gladia.io/example/video-transcription/short-video.mp4",
        "required": false
      },
      {
        "in": "formData",
        "type": "url",
        "name": "video_url",
        "example": "http://files.gladia.io/example/video-transcription/short-video.mp4",
        "required": false
      },
      {
        "in": "formData",
        "type": "enum",
        "name": "language_behaviour",
        "example": "automatic single language",
        "required": false,
        "enumValues": [
          "manual",
          "automatic single language",
          "automatic multiple languages"
        ]
      },
      {
        "in": "formData",
        "type": "enum",
        "name": "language",
        "example": "english",
        "required": false,
        "enumValues": [
          "afrikaans",
          "albanian",
          "amharic",
          "arabic",
          "armenian",
          "assamese",
          "azerbaijani",
          "bashkir",
          "basque",
          "belarusian",
          "bengali",
          "bosnian",
          "breton",
          "bulgarian",
          "catalan",
          "chinese",
          "croatian",
          "czech",
          "danish",
          "dutch",
          "english",
          "estonian",
          "faroese",
          "finnish",
          "french",
          "galician",
          "georgian",
          "german",
          "greek",
          "gujarati",
          "haitian creole",
          "hausa",
          "hawaiian",
          "hebrew",
          "hindi",
          "hungarian",
          "icelandic",
          "indonesian",
          "italian",
          "japanese",
          "javanese",
          "kannada",
          "kazakh",
          "khmer",
          "korean",
          "lao",
          "latin",
          "latvian",
          "lingala",
          "lithuanian",
          "luxembourgish",
          "macedonian",
          "malagasy",
          "malay",
          "malayalam",
          "maltese",
          "maori",
          "marathi",
          "mongolian",
          "myanmar",
          "nepali",
          "norwegian",
          "nynorsk",
          "occitan",
          "pashto",
          "persian",
          "polish",
          "portuguese",
          "punjabi",
          "romanian",
          "russian",
          "sanskrit",
          "serbian",
          "shona",
          "sindhi",
          "sinhala",
          "slovak",
          "slovenian",
          "somali",
          "spanish",
          "sundanese",
          "swahili",
          "swedish",
          "tagalog",
          "tajik",
          "tamil",
          "tatar",
          "telugu",
          "thai",
          "tibetan",
          "turkish",
          "turkmen",
          "ukrainian",
          "urdu",
          "uzbek",
          "vietnamese",
          "welsh",
          "wolof",
          "yiddish",
          "yoruba"
        ]
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_noise_reduction",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "string",
        "name": "transcription_hint",
        "example": "",
        "required": false
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_diarization",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_direct_translate",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "enum",
        "name": "target_translation_language",
        "example": "english",
        "required": false,
        "enumValues": [
          "afrikaans",
          "albanian",
          "amharic",
          "arabic",
          "armenian",
          "assamese",
          "azerbaijani",
          "bashkir",
          "basque",
          "belarusian",
          "bengali",
          "bosnian",
          "breton",
          "bulgarian",
          "catalan",
          "chinese",
          "croatian",
          "czech",
          "danish",
          "dutch",
          "english",
          "estonian",
          "faroese",
          "finnish",
          "french",
          "galician",
          "georgian",
          "german",
          "greek",
          "gujarati",
          "haitian creole",
          "hausa",
          "hawaiian",
          "hebrew",
          "hindi",
          "hungarian",
          "icelandic",
          "indonesian",
          "italian",
          "japanese",
          "javanese",
          "kannada",
          "kazakh",
          "khmer",
          "korean",
          "lao",
          "latin",
          "latvian",
          "lingala",
          "lithuanian",
          "luxembourgish",
          "macedonian",
          "malagasy",
          "malay",
          "malayalam",
          "maltese",
          "maori",
          "marathi",
          "mongolian",
          "myanmar",
          "nepali",
          "norwegian",
          "nynorsk",
          "occitan",
          "pashto",
          "persian",
          "polish",
          "portuguese",
          "punjabi",
          "romanian",
          "russian",
          "sanskrit",
          "serbian",
          "shona",
          "sindhi",
          "sinhala",
          "slovak",
          "slovenian",
          "somali",
          "spanish",
          "sundanese",
          "swahili",
          "swedish",
          "tagalog",
          "tajik",
          "tamil",
          "tatar",
          "telugu",
          "thai",
          "tibetan",
          "turkish",
          "turkmen",
          "ukrainian",
          "urdu",
          "uzbek",
          "vietnamese",
          "welsh",
          "wolof",
          "yiddish",
          "yoruba"
        ]
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_text_emotion_recognition",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_summarization",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "boolean",
        "name": "toggle_chapterization",
        "example": false,
        "required": false
      },
      {
        "in": "formData",
        "type": "integer",
        "name": "diarization_max_speakers",
        "example": 10,
        "required": false
      },
      {
        "in": "formData",
        "type": "enum",
        "name": "output_format",
        "example": "json",
        "required": false,
        "enumValues": [
          "json",
          "srt",
          "vtt",
          "txt",
          "plain"
        ]
      }
    ],
    "hasSamplesParam": false
  }
];