"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getOutputModelType = exports.getInputModelType = exports.getModelValuesName = exports.getModelTypeName = exports.getMethodName = exports.getDefaultValueName = exports.getEndpointsByInputOutput = exports.getEndpoints = void 0;
var get_endpoints_1 = require("./get-endpoints");
Object.defineProperty(exports, "getEndpoints", { enumerable: true, get: function () { return get_endpoints_1.getEndpoints; } });
Object.defineProperty(exports, "getEndpointsByInputOutput", { enumerable: true, get: function () { return get_endpoints_1.getEndpointsByInputOutput; } });
var get_default_value_name_1 = require("./get-default-value-name");
Object.defineProperty(exports, "getDefaultValueName", { enumerable: true, get: function () { return get_default_value_name_1.getDefaultValueName; } });
var get_method_name_1 = require("./get-method-name");
Object.defineProperty(exports, "getMethodName", { enumerable: true, get: function () { return get_method_name_1.getMethodName; } });
var get_model_type_name_1 = require("./get-model-type-name");
Object.defineProperty(exports, "getModelTypeName", { enumerable: true, get: function () { return get_model_type_name_1.getModelTypeName; } });
var get_model_values_name_1 = require("./get-model-values-name");
Object.defineProperty(exports, "getModelValuesName", { enumerable: true, get: function () { return get_model_values_name_1.getModelValuesName; } });
var get_input_model_type_1 = require("./get-input-model-type");
Object.defineProperty(exports, "getInputModelType", { enumerable: true, get: function () { return get_input_model_type_1.getInputModelType; } });
var get_output_model_type_1 = require("./get-output-model-type");
Object.defineProperty(exports, "getOutputModelType", { enumerable: true, get: function () { return get_output_model_type_1.getOutputModelType; } });
